# Generated by Django 5.0.8 on 2024-09-25 10:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
            ],
            options={
                'db_table': 'Appointment',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('reg_no', models.CharField(max_length=15, unique=True)),
                ('is_default', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Car',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Customer', 'Customer'), ('Mechanic', 'Mechanic'), ('Manager', 'Manager')], max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
                ('street_address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent')], default='Pending', max_length=20)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Part',
            },
        ),
        migrations.CreateModel(
            name='PartInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PredefinedCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
            ],
            options={
                'db_table': 'PredefinedCar',
            },
        ),
        migrations.CreateModel(
            name='PredefinedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'PredefinedPart',
            },
        ),
        migrations.CreateModel(
            name='PredefinedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'PredefinedTask',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labor_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default='Pending', max_length=50)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Quote',
            },
        ),
        migrations.CreateModel(
            name='QuotePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'QuotePart',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Requested', 'Requested'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Canceled', 'Canceled')], default='Requested', max_length=20)),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='ServiceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'service_report',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'db_table': 'ServiceType',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_part', models.CharField(max_length=100)),
                ('steps', models.JSONField()),
            ],
            options={
                'db_table': 'skill',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20)),
            ],
            options={
                'db_table': 'Task',
            },
        ),
        migrations.CreateModel(
            name='TaskReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comments', models.TextField()),
                ('Images', models.ImageField(blank=True, null=True, upload_to='report_images/')),
                ('status', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odometer', models.IntegerField()),
                ('battery', models.IntegerField()),
                ('tires', models.IntegerField()),
                ('oilLevel', models.IntegerField()),
                ('brakePads', models.IntegerField()),
                ('airFilter', models.IntegerField()),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car')),
            ],
            options={
                'db_table': 'CarHealth',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user')),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user')),
            ],
            options={
                'db_table': 'Manager',
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.user')),
                ('current_workload', models.IntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'Mechanic',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='User_email_ffa2e0_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='User_role_93b446_idx'),
        ),
        migrations.AddField(
            model_name='partinvoice',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_invoices', to='core.invoice'),
        ),
        migrations.AddField(
            model_name='partinvoice',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.part'),
        ),
        migrations.AddIndex(
            model_name='predefinedcar',
            index=models.Index(fields=['make', 'model', 'year'], name='PredefinedC_make_77b5ae_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='predefinedcar',
            unique_together={('make', 'model', 'year')},
        ),
        migrations.AddField(
            model_name='part',
            name='predefined_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.predefinedcar'),
        ),
        migrations.AddField(
            model_name='car',
            name='predefined_car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.predefinedcar'),
        ),
        migrations.AddField(
            model_name='part',
            name='predefined_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.predefinedpart'),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.part'),
        ),
        migrations.AddField(
            model_name='quotepart',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.quote'),
        ),
        migrations.AddField(
            model_name='quote',
            name='parts',
            field=models.ManyToManyField(related_name='quotes', through='core.QuotePart', to='core.part'),
        ),
        migrations.AddField(
            model_name='service',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car'),
        ),
        migrations.AddField(
            model_name='quote',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='core.service'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.service'),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reports', to='core.service'),
        ),
        migrations.AddIndex(
            model_name='servicetype',
            index=models.Index(fields=['name'], name='ServiceType_name_335dbb_idx'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicetype'),
        ),
        migrations.AddField(
            model_name='predefinedtask',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_tasks', to='core.servicetype'),
        ),
        migrations.AddField(
            model_name='predefinedpart',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predefined_parts', to='core.servicetype'),
        ),
        migrations.AddField(
            model_name='skill',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='core.predefinedcar'),
        ),
        migrations.AddField(
            model_name='task',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service'),
        ),
        migrations.AddField(
            model_name='task',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicetype'),
        ),
        migrations.AddField(
            model_name='taskreport',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reports', to='core.task'),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='task_reports',
            field=models.ManyToManyField(related_name='service_reports', to='core.taskreport'),
        ),
        migrations.AddIndex(
            model_name='carhealth',
            index=models.Index(fields=['car'], name='CarHealth_car_id_db30fb_idx'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='core.customer'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['user'], name='Customer_user_id_7876b0_idx'),
        ),
        migrations.AddField(
            model_name='car',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer'),
        ),
        migrations.AddIndex(
            model_name='manager',
            index=models.Index(fields=['user'], name='Manager_user_id_ad79e9_idx'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mechanic'),
        ),
        migrations.AddIndex(
            model_name='mechanic',
            index=models.Index(fields=['user'], name='Mechanic_user_id_74ac76_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['predefined_car'], name='Part_predefi_82242e_idx'),
        ),
        migrations.AddIndex(
            model_name='part',
            index=models.Index(fields=['predefined_part'], name='Part_predefi_f562af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='part',
            unique_together={('predefined_car', 'predefined_part')},
        ),
        migrations.AddIndex(
            model_name='quotepart',
            index=models.Index(fields=['quote'], name='QuotePart_quote_i_11a1da_idx'),
        ),
        migrations.AddIndex(
            model_name='quotepart',
            index=models.Index(fields=['part'], name='QuotePart_part_id_ef26f0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quotepart',
            unique_together={('quote', 'part')},
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['service'], name='Quote_service_d29ce8_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['service'], name='Appointment_service_850688_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date'], name='Appointment_date_a7371d_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['time'], name='Appointment_time_ad47b9_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['car'], name='Service_car_id_4dda5a_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['service_type'], name='Service_service_3035f4_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status'], name='Service_status_058ef6_idx'),
        ),
        migrations.AddIndex(
            model_name='predefinedtask',
            index=models.Index(fields=['service_type'], name='PredefinedT_service_ba7cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='predefinedpart',
            index=models.Index(fields=['name'], name='PredefinedP_name_26a3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['vehicle'], name='skill_vehicle_7be2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='servicereport',
            index=models.Index(fields=['service'], name='service_rep_service_a32aea_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['service'], name='Feedback_service_563a75_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['customer'], name='Feedback_custome_167e20_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['customer'], name='Car_custome_bd2bc5_idx'),
        ),
        migrations.AddIndex(
            model_name='car',
            index=models.Index(fields=['predefined_car'], name='Car_predefi_41fa79_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['service'], name='Task_service_c5e5be_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assigned_to'], name='Task_assigne_cb1d91_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['status'], name='Task_status_a97274_idx'),
        ),
    ]
