# Generated by Django 5.0.7 on 2024-09-29 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
